#!/usr/bin/env bash

echo "initialing..."
terraform init

echo "validating..."
terraform validate
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
    echo "[ERROR]: validation failed..."
    exit $EXIT_CODE
fi

echo "generating terraform plan..."
terraform plan -var-file=terraform.tfvars -out=tfplan

echo "applying..."
terraform apply tfplan
exit 0
